### ISSUE TITLE
Cannot connect more than 6 devices on OSX El Capitan

### ISSUE THREAD

**Issue by mhle** [sandeepmistry/node-core-bluetooth#1]
Getting the following error when trying to connect to more than 6 devices on OSX El Capitan:

```
node-core-bluetooth/lib/central-manager-delegate.js:146
  }.bind(mapDelegate(self), mapPeripheral(identifier), error));
                     ^
ReferenceError: self is not defined
    at /node-core-bluetooth/lib/central-manager-delegate.js:146:22
    at /node-core-bluetooth/node_modules/NodObjC/lib/core.js:252:31
    at /node-core-bluetooth/node_modules/NodObjC/node_modules/ffi/lib/callback.js:52:23
```

confirmed issue does not exist on OSX Yosemite

**Comment by sandeepmistry** [comment]
https://github.com/sandeepmistry/node-core-bluetooth/commit/b43d70e3c4caf685251cb049ff9abee11826c773 should resolve the exception.

However, based on https://github.com/sandeepmistry/noble/issues/256 OS X 10.11 can still only to 6 peripherals at a time.
